// ! posts
export const FETCH_POSTS_REQUEST = "FETCH_POSTS_REQUEST";
export const FETCH_POSTS_SUCCESS = "FETCH_POSTS_SUCCESS";
export const FETCH_POSTS_FAILURE = "FETCH_POSTS_FAILURE";

// ! comments
export const FETCH_COMMENTS_REQUEST = "FETCH_COMMENTS_REQUEST";
export const FETCH_COMMENTS_SUCCESS = "FETCH_COMMENTS_SUCCESS";
export const FETCH_COMMENTS_FAILURE = "FETCH_COMMENTS_FAILURE";

// ! pagination
export const SET_PAGE = "SET_PAGE";
export const SET_PAGE_SIZE = "SET_PAGE_SIZE";
export const SET_TOTAL_POSTS = "SET_TOTAL_POSTS";

// ! sort
export const SORT_POSTS_BY_TITLE = "SORT_POSTS_BY_TITLE";

// ! onePosts
export const FETCH_ONE_POST_REQUEST = "FETCH_ONE_POST_REQUEST";
export const FETCH_ONE_POST_SUCCESS = "FETCH_ONE_POST_SUCCESS";
export const FETCH_ONE_POST_FAILURE = "FETCH_ONE_POST_FAILURE";

//!  user
export const FETCH_ONE_USER_REQUEST = "FETCH_ONE_USER_REQUEST";
export const FETCH_ONE_USER_SUCCESS = "FETCH_ONE_USER_SUCCESS";
export const FETCH_ONE_USER_FAILURE = "FETCH_ONE_USER_FAILURE";
